
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `bmtest`=list(
        `type`="article", 
        `author`="Karch, J.D.", 
        `year`=2023, 
        `title`="bmtest: A Jamovi Module for Brunner\u2013Munzel\u2019s Test\u2014A Robust Alternative to Wilcoxon\u2013Mann\u2013Whitney\u2019s Test", 
        `publisher`="Psych", 
        `url`="https://doi.org/10.3390/psych5020026", 
        `doi`="10.3390/psych5020026", 
        `volume`=5, 
        `pages`="127-141"), 
    `bmtest2`=list(
        `type`="article", 
        `author`="Karch, J.D.", 
        `year`=2021, 
        `title`="Psychologists Should Use Brunner-Munzel\u2019s Instead of Mann-Whitney\u2019s U Test as the Default Nonparametric Procedure", 
        `publisher`="Advances in Methods and Practices in Psychological Science", 
        `url`="https://doi.org/10.1177/2515245921999", 
        `doi`="10.1177/2515245921999", 
        `volume`=4, 
        `issue`=2))
