
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `bmtest`=list(
        `type`="article", 
        `author`="Karch, J.D.", 
        `year`=2023, 
        `title`="bmtest: A Jamovi Module for Brunner\u2013Munzel\u2019s Test\u2014A Robust Alternative to Wilcoxon\u2013Mann\u2013Whitney\u2019s Test", 
        `publisher`="Psych", 
        `url`="https://doi.org/10.3390/psych5020026", 
        `doi`="10.3390/psych5020026", 
        `volume`=5, 
        `pages`="127-141"))
