
# This file is automatically generated, you probably don't want to edit this

bmtestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bmtestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            hypothesis = "different",
            relEff = FALSE,
            ci = FALSE,
            ciWidth = 95,
            miss = "perAnalysis",
            asym = TRUE,
            randomPerm = FALSE,
            fullPerm = FALSE,
            n_perm = 10000, ...) {

            super$initialize(
                package="bmtest",
                name="bmtest",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "different",
                    "oneGreater",
                    "twoGreater"),
                default="different")
            private$..relEff <- jmvcore::OptionBool$new(
                "relEff",
                relEff,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "perAnalysis",
                    "listwise"),
                default="perAnalysis")
            private$..asym <- jmvcore::OptionBool$new(
                "asym",
                asym,
                default=TRUE)
            private$..randomPerm <- jmvcore::OptionBool$new(
                "randomPerm",
                randomPerm,
                default=FALSE)
            private$..fullPerm <- jmvcore::OptionBool$new(
                "fullPerm",
                fullPerm,
                default=FALSE)
            private$..n_perm <- jmvcore::OptionNumber$new(
                "n_perm",
                n_perm,
                min=40,
                default=10000)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..relEff)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..miss)
            self$.addOption(private$..asym)
            self$.addOption(private$..randomPerm)
            self$.addOption(private$..fullPerm)
            self$.addOption(private$..n_perm)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        hypothesis = function() private$..hypothesis$value,
        relEff = function() private$..relEff$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        miss = function() private$..miss$value,
        asym = function() private$..asym$value,
        randomPerm = function() private$..randomPerm$value,
        fullPerm = function() private$..fullPerm$value,
        n_perm = function() private$..n_perm$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..hypothesis = NA,
        ..relEff = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..miss = NA,
        ..asym = NA,
        ..randomPerm = NA,
        ..fullPerm = NA,
        ..n_perm = NA)
)

bmtestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bmtestResults",
    inherit = jmvcore::Group,
    active = list(
        bmtest = function() private$.items[["bmtest"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Independent Samples Brunner Munzel Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="bmtest",
                title="Independent Samples Brunner Munzel Test",
                rows="(vars)",
                clearWith=list(
                    "group",
                    "hypothesis",
                    "miss",
                    "ciWidth",
                    "n_perm"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="test[asym]", 
                        `title`="", 
                        `type`="text", 
                        `content`="t-Approximation", 
                        `visible`="(asym)"),
                    list(
                        `name`="stat[asym]", 
                        `title`="Statistic", 
                        `type`="number", 
                        `visible`="(asym)"),
                    list(
                        `name`="df[asym]", 
                        `title`="df", 
                        `type`="number", 
                        `visible`="(asym)"),
                    list(
                        `name`="p[asym]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(asym)"),
                    list(
                        `name`="relEff[asym]", 
                        `title`="Relative Effect", 
                        `type`="number", 
                        `visible`="(relEff && asym)"),
                    list(
                        `name`="cil[asym]", 
                        `title`="Lower", 
                        `type`="number", 
                        `visible`="(relEff && ci && asym)"),
                    list(
                        `name`="ciu[asym]", 
                        `title`="Upper", 
                        `type`="number", 
                        `visible`="(relEff && ci && asym)"),
                    list(
                        `name`="var", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="test[randomPerm]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Random Permutations", 
                        `visible`="(randomPerm)"),
                    list(
                        `name`="stat[randomPerm]", 
                        `title`="Statistic", 
                        `type`="number", 
                        `visible`="(randomPerm)"),
                    list(
                        `name`="p[randomPerm]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(randomPerm)"),
                    list(
                        `name`="relEff[randomPerm]", 
                        `title`="Relative Effect", 
                        `type`="number", 
                        `visible`="(relEff && randomPerm)"),
                    list(
                        `name`="cil[randomPerm]", 
                        `title`="Lower", 
                        `type`="number", 
                        `visible`="(relEff && ci && randomPerm)"),
                    list(
                        `name`="ciu[randomPerm]", 
                        `title`="Upper", 
                        `type`="number", 
                        `visible`="(relEff && ci && randomPerm)"),
                    list(
                        `name`="test[fullPerm]", 
                        `title`="", 
                        `type`="text", 
                        `content`="All Permutations", 
                        `visible`="(fullPerm)"),
                    list(
                        `name`="stat[fullPerm]", 
                        `title`="Statistic", 
                        `type`="number", 
                        `visible`="(fullPerm)"),
                    list(
                        `name`="p[fullPerm]", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(fullPerm)"),
                    list(
                        `name`="relEff[fullPerm]", 
                        `title`="Relative Effect", 
                        `type`="number", 
                        `visible`="(relEff && fullPerm)"))))}))

bmtestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bmtestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "bmtest",
                name = "bmtest",
                version = c(1,0,0),
                options = options,
                results = bmtestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Independent Samples Brunner Munzel Test
#'
#' The Brunner–Munzel test for stochastic equality of two samples, which is 
#' also known as the Generalized Wilcoxon test.
#' 
#'
#' @examples
#' library(jmv) # to get ToothGrowth data set
#' data('ToothGrowth')
#' bmtest(formula = len ~ supp, data = ToothGrowth)
#' # INDEPENDENT SAMPLES BRUNNER MUNZEL TEST
#' #
#' # Independent Samples Brunner Munzel Test
#' # ----------------------------------------------------------------
#' #                             Statistic    df          p
#' # ----------------------------------------------------------------
#' #   len    t-Approximation    -1.896526    54.67724    0.0631786
#' # ----------------------------------------------------------------
#' #   Note. Ha P(OJ > VC) + ½P(OJ = VC) != ½
#'
#' @param data the data as a data frame
#' @param vars the dependent variables (not necessary when using a formula,
#'   see the examples)
#' @param group the grouping variable with two levels (not necessary when
#'   using a formula, see the examples)
#' @param hypothesis \code{'different'} (default), \code{'oneGreater'} or
#'   \code{'twoGreater'}, the alternative hypothesis; group 1 different to group
#'   2, group 1 greater than group 2, and group 2 greater than group 1
#'   respectively
#' @param relEff \code{TRUE} or \code{FALSE} (default), provide estimate of
#'   relative effect
#' @param ci \code{TRUE} or \code{FALSE} (default), provide confidence
#'   intervals
#' @param ciWidth a number between 50 and 99.9 (default: 95), the width of
#'   confidence intervals
#' @param miss \code{'perAnalysis'} or \code{'listwise'}, how to handle
#'   missing values; \code{'perAnalysis'} excludes missing values for individual
#'   dependent variables, \code{'listwise'} excludes a row from all analyses if
#'   one of its entries is missing.
#' @param asym \code{TRUE} (default) or \code{FALSE}, Compute p values and
#'   confidence intervals using t-approximation
#' @param randomPerm \code{TRUE} (default) or \code{FALSE}, Compute p values
#'   and confidence intervals using random permutations
#' @param fullPerm \code{TRUE} (default) or \code{FALSE}, Compute p values and
#'   confidence intervals using ALL permutations
#' @param n_perm a integer (default 10000), the number of random permutations
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$bmtest} \tab \tab \tab \tab \tab a table containing the Brunner Munzel Test results \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$bmtest$asDF}
#'
#' \code{as.data.frame(results$bmtest)}
#'
#' @export
bmtest <- function(
    data,
    vars,
    group,
    hypothesis = "different",
    relEff = FALSE,
    ci = FALSE,
    ciWidth = 95,
    miss = "perAnalysis",
    asym = TRUE,
    randomPerm = FALSE,
    fullPerm = FALSE,
    n_perm = 10000,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bmtest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(vars))
            vars <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                required=TRUE)
        if (missing(group))
            group <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                subset="1")
    }

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- bmtestOptions$new(
        vars = vars,
        group = group,
        hypothesis = hypothesis,
        relEff = relEff,
        ci = ci,
        ciWidth = ciWidth,
        miss = miss,
        asym = asym,
        randomPerm = randomPerm,
        fullPerm = fullPerm,
        n_perm = n_perm)

    analysis <- bmtestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

